# Getting ready for object-oriented programming

Dalam bab ini kami secara singkat meninjau **functions dan data structures**, karena mereka membangun blok pemrograman berorientasi objek. Kemudian kita beralih ke definisi konseptual **objects dan classes**.

## Intro to Object Oriented Programming in Python

### What's Object-Oriented Programming? (OOP)

* Cara untuk membangun kode yang fleksibel dan dapat direproduksi
* Mengembangkan *building blocks* untuk mengembangkan **modules dan libraries** yang lebih maju

<img src="figure/oop.png" width=500px height=500px align=left />

### Imperative Style and OOP Style

**IMPERATIVE**

In [3]:
our_list = [1, 2, 3]
for item in our_list:
    print("Item {}".format(item))

Item 1
Item 2
Item 3


**OOP**

In [4]:
class PrintList:
    
    def __init__(self, numberlist):
        self.numberlist = numberlist
        
    def print_list(self):
        for item in self.numberlist:
            print("Item {}".format(item))
            
A = PrintList([1, 2, 3, 4])
A.print_list()

Item 1
Item 2
Item 3
Item 4


### All Python libraries work together

<img src="figure/all-libraries.png" width=500px height=500px align=left />

### Creating functions

Dalam latihan ini, kami akan meninjau functions, karena merupakan building blocks utama dari program berorientasi objek.

Untuk ini, kita akan membuat functions `average_numbers()` untuk membuat rata-rata list angka. Ingat bahwa list adalah tipe data dasar dalam Python yang dapat kita bangun menggunakan notasi braket `[]`.

Berikut adalah contoh fungsi yang mengembalikan kuadrat dari bilangan bulat:

In [6]:
# Mendifinisikan functions
def square_function(x):
    x_squared =  x**2
    return x_squared

# Memanggil functions
square_function(4)

16

In [7]:
# Create function that returns the average of an integer list
def average_numbers(num_list): 
    avg = sum(num_list)/float(len(num_list)) # divide by length of list
    return avg

# Take the average of a list: my_avg
my_avg = average_numbers([1, 2, 3, 4, 5, 6])

# Print out my_avg
print(my_avg)

3.5


**Catatan** : Sekarang Anda telah membuat suatu functions, cobalah bermain-main dengan menambahkan list Anda sendiri.

In [9]:
average_numbers([4, 6, 3, 2])

3.75

### Creating a complex data type

Kita akan melihat lebih dekat pada fleksibilitas tipe data list, dengan membuat **list of lists**.

Dalam Python, `list` dapat terdiri dari string sederhana, integer, atau kombinasi keduanya.

In [11]:
list = [1, 2]

Dalam membuat list of lists, kami membangun konsep NumPy array.

In [12]:
# Create a list that contains two lists: matrix
matrix = [[1,2,3,4], [5,6,7,8]]

# Print the matrix list
print(matrix)

[[1, 2, 3, 4], [5, 6, 7, 8]]


**Catatan** : Apa yang terjadi ketika Anda membuat dua lists dalam list? Bagaimana Anda bisa mengakses elemen-elemen itu? Coba buat list bersarang (*nested*) `tripply` dan temukan jawabannya.

In [13]:
tripply = [[5, 4, 3, 2], [3, 2, 1, 4], [6, 7, 4, 2]]

In [15]:
tripply[1]

[3, 2, 1, 4]

In [16]:
tripply[2][1]

7

In [18]:
tripply[1] = 'string di dalam list'
tripply

[[5, 4, 3, 2], 'string di dalam list', [6, 7, 4, 2]]

In [19]:
tripply.append(2.1)

In [20]:
tripply

[[5, 4, 3, 2], 'string di dalam list', [6, 7, 4, 2], 2.1]

## Introduction to NumPy Internals

### What's NumPy?

NumPy adalah package untuk komputasi ilmiah dengan Python.

* Menggunakan matriks dan vektor sebagai struktur data
* Sempurna untuk ilmu data, di mana data diletakkan dalam format seperti tabel

### NumPy as a building block to Pandas

<img src="figure/pandas-series.png" width=500px height=500px align=left />

### Creating NumPy arrays

<img src="figure/arrays.png" width=500px height=500px align=left />

### NumPy Array example

In [21]:
import numpy as np

our_array = np.array([2,3,4])
print(our_array)

[2 3 4]


In [22]:
type(our_array)

numpy.ndarray

### Creating Multi-Dimensional Arrays

In [24]:
np.array([[ 0, 1, 2, 3, 4],
          [ 5, 6, 7, 8, 9],
          [10, 11, 12, 13, 14]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
np.array([6, 7, 8])

array([6, 7, 8])

### Create a function that returns a NumPy array

Kami akan membuat NumPy array dari tipe data float (numerik) sehingga kami dapat bekerja dengan objects data multi-dimensi, seperti kolom dan baris dalam spreadsheet.

In [27]:
# List input: my_matrix
my_matrix = [[1,2,3,4], [5,6,7,8]] 

# Function that converts lists to arrays: return_array
def return_array(matrix):
    array = np.array(matrix, dtype = float)
    return array
    
# Call return_array on my_matrix, and print the output
print(return_array(my_matrix))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


**Catatan** : Sekarang Anda telah membuat NumPy array, lihat dokumen NumPy (dengan googling) dan selidiki yang dapat diambil oleh array jenis data lainnya (sebagai argumen).

## Introduction to Objects and Classes

### What is a class?

Potongan kode yang dapat digunakan kembali yang memiliki **methods dan variables**.

In [28]:
class PrintList:
    
    def __init__(self, numberlist):
        self.numberlist = numberlist
        
    def print_list(self):
        for item in self.numberlist:
            print("Item {}".format(item))
            
A = PrintList([1, 2, 3, 4])
A.print_list()

Item 1
Item 2
Item 3
Item 4


### OOP Vocabulary

* Imperative
  * Variable
  * Function
* OOP
  * Attribute/Field
  * Method

### A Class is a template for an object

**Class --> Object**

### Declaring a Class

Kita akan bekerja membangun class, yang merupakan cara untuk mengatur functions dan variables dengan Python. Untuk memulainya, mari kita lihat cara paling sederhana untuk membuat class.

In [29]:
# Declaring a Class
class Dinosaur:
    pass

In [30]:
# Used in Python 3, with/without parentheses
class Dinosaur():
    pass

# Used in Python 2
class Dinosaur(object):
    pass

In [31]:
# An object is an instance of a class.
Tyrannosaurus = Dinosaur()

In [32]:
Tyrannosaurus

In [34]:
# Create a class: DataShell
class DataShell: 
    pass

**Catatan** : Coba buat class yang berbeda dengan nama yang berbeda. Lihat konvensi penamaan seperti apa yang akan diterima Python.

In [35]:
class GoingToMarket:
    pass

In [36]:
class UploadData:
    pass

### Difference between a class and an object

Objects adalah instance dari class, yang dapat memiliki variables dan functions. Bisa juga dikatakan sebagai template.