# 1. Foundations for efficiencies

Dalam bab ini, Anda akan belajar apa artinya menulis kode Python yang efisien. Anda akan menjelajahi Library Standar Python, mempelajari tentang array NumPy, dan berlatih menggunakan beberapa alat bawaan Python. Bab ini membangun fondasi untuk konsep-konsep yang dibahas di depan.

### A taste of things to come

Dalam latihan ini, Anda akan mengeksplorasi cara **Non-Pythonic** dan **Pythonic** untuk looping melalui list.

Misalkan Anda ingin mengumpulkan nama-nama dalam variabel list `names` yang memiliki enam huruf atau lebih. Dalam bahasa pemrograman lain, tipikal pendekatan adalah membuat variabel indeks (`i`), menggunakan `i` untuk beralih (*iterate*) ke list, dan menggunakan pernyataan `if` untuk mengumpulkan nama-nama dengan enam huruf atau lebih:

In [22]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

In [23]:
# Print the list created using the Non-Pythonic approach
i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [25]:
# A more Pythonic approach
# Print the list created by looping over the contents of names
better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [26]:
# The best Pythonic way
# Print the list created by using list comprehension
best_list = [name for name in names if len(name) >= 6]
print(best_list)

['Kramer', 'Elaine', 'George', 'Newman']


**Note**: Perlu diperhatikan! `Pythonic code == efficient code`

## Building with builtins

### The Python Standard Library

* [Python 3.6 Standard Library](https://docs.python.org/3.6/library/index.html)
  * Bagian dari setiap instalasi Python standar
* Built-in types
  * `list` , `tuple` , `set` , `dict` , dan lainnya
* Built-in functions
  * `print()` , `len()` , `range()` , `round()` , `enumerate()` , `map()` , `zip()` , dan lainnya
* Built-in modules
  * `os` , `sys` , `itertools` , `collections` , `math` , dan lainnya

### Built-in function: `range()`

Kode list angka secara eksplisit

In [3]:
nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(nums)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Menggunakan `range()` untuk membuat list yang sama

In [2]:
# range(start, stop)
nums = range(0, 11)

nums_list = list(nums)
print(nums_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
# range(stop)
nums = range(11)

nums_list = list(nums)
print(nums_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Menggunakan `range()` dengan nilai `step`

In [5]:
# rangeg(start, stop, step)
even_nums = range(2, 11, 2)

even_nums_list = list(even_nums)
print(even_nums_list)

[2, 4, 6, 8, 10]


### Built-in function: `enumerate()`

Membuat list objek yang diindeks

In [6]:
letters = ['a', 'b', 'c', 'd']

indexed_letters = enumerate(letters)

indexed_letters_list = list(indexed_letters)
print(indexed_letters_list)

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]


In [15]:
# Menampilkan indeks dengan list comprehension
[letters[1] for letters in indexed_letters_list]

['a', 'b', 'c', 'd']

Dapat menentukan nilai awal (`start`)

In [16]:
letters = ['a', 'b', 'c', 'd']

indexed_letters2 = enumerate(letters, start=5)

indexed_letters2_list = list(indexed_letters2)
print(indexed_letters2_list)

[(5, 'a'), (6, 'b'), (7, 'c'), (8, 'd')]


### Built-in function: `map()`

Menerapkan fungsi di atas objek

In [18]:
nums = [1.5, 2.3, 3.4, 4.6, 5.0]

rnd_nums = map(round, nums)
print(list(rnd_nums))

[2, 2, 3, 5, 5]


`map()` dengan `lambda` ( *anonymous function* )

In [21]:
nums = [1, 2, 3, 4, 5]

sqrd_nums = map(lambda x: x ** 2, nums)
print(list(sqrd_nums))

[1, 4, 9, 16, 25]


### Built-in practice: `range()`

In [27]:
# Create a range object that goes from 0 to 5
nums = range(0, 6)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
# range(start, stop, step)
nums_list2 = [*range(1, 12, 2)]
print(nums_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9, 11]


**Note** : Perhatikan bahwa menggunakan fungsi `range()` Python memungkinkan Anda untuk membuat objek rentang angka tanpa mengetikkannya secara eksplisit. Anda dapat mengubah objek rentang menjadi *list* dengan menggunakan fungsi `list()` atau dengan membongkarnya menjadi *list* menggunakan karakter bintang (`*`).

### Built-in practice: `enumerate()`

Dalam latihan ini, Anda akan berlatih menggunakan fungsi bawaan Python yaitu `enumerate()`. Fungsi ini berguna untuk mendapatkan **list yang diindeks**. Misalnya, Anda memiliki list orang yang tiba di pesta yang di undang ke rumah Anda. List ini diurutkan pada saat kedatangan (Jerry adalah yang pertama tiba, diikuti oleh Kramer, dll.):

In [29]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

Jika Anda ingin melampirkan indeks yang mewakili urutan kedatangan seseorang, Anda dapat menggunakan `for` loop:

In [31]:
indexed_names = []

for i in range(len(names)):
    index_name = (i, names[i])
    indexed_names.append(index_name)
    
print(indexed_names)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]


Tapi, itu bukan solusi yang paling efisien. Mari kita menjelajahi cara menggunakan `enumerate()` untuk membuatnya lebih efisien.

In [28]:
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, start=1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


**Note** : Menggunakan fungsi bawaan Python `enumerate()` memungkinkan Anda untuk membuat indeks untuk setiap item dalam objek yang Anda berikan. Anda dapat menggunakan *list comprehensions*, atau bahkan membongkar objek *enumerate* langsung ke list, untuk menulis satu baris kode sederhana yang lebih bagus.

### Built-in practice: map()

Dalam latihan ini, Anda akan berlatih menggunakan fungsi bawaan Python `map()` untuk menerapkan fungsi ke setiap elemen objek. 

Misalkan Anda ingin membuat list baru (bernama `names_uppercase`) yang mengubah semua huruf dalam setiap nama menjadi huruf besar. Anda bisa melakukannya dengan loop di bawah ini:

In [38]:
names_uppercase = []

for name in names:
    names_uppercase.append(name.upper())
    
print(names_uppercase)

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


Mari kita telusuri menggunakan fungsi `map()` untuk melakukan ini lebih efisien dalam satu baris kode.

In [39]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


**Note** : Anda menggunakan fungsi bawaan Python `map()` untuk menerapkan metode `str.upper()` ke setiap elemen dalam objek `names`. Selanjutnya dalam kursus ini, Anda akan mengeksplorasi bagaimana menggunakan `map()` dapat memberikan beberapa peningkatan efisiensi pada kode Anda.

## The power of NumPy arrays

### NumPy array overview

Alternatif untuk Python lists

In [40]:
nums_list = list(range(5))
print(nums_list)

[0, 1, 2, 3, 4]


In [42]:
import numpy as np

nums_np = np.array(range(5))
print(nums_np)

[0 1 2 3 4]


In [43]:
# NumPy array homogeneity
nums_np_ints = np.array([1, 2, 3])
print(nums_np_ints)

[1 2 3]


In [44]:
nums_np_ints.dtype

dtype('int64')

In [45]:
nums_np_floats = np.array([1, 2.5, 3])
print(nums_np_floats)

[1.  2.5 3. ]


In [46]:
nums_np_floats.dtype

dtype('float64')

### NumPy array broadcasting

Python lists tidak mendukung broadcasting

In [47]:
nums = [-2, -1, 0, 1, 2]
nums ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Cara broadcasting menggunakan pendekatan *list* :

In [51]:
# For loop (inefficient option)
sqrd_nums = []
for num in nums:
    sqrd_nums.append(num ** 2) 
print(sqrd_nums)

[4, 1, 0, 1, 4]


In [52]:
# List comprehension (better option but not best)
sqrd_nums = [num ** 2 for num in nums]
print(sqrd_nums)

[4, 1, 0, 1, 4]


In [53]:
# NumPy array broadcasting for the win!
nums_np = np.array([-2, -1, 0, 1, 2])
nums_np ** 2

array([4, 1, 0, 1, 4])

### Basic 1-D indexing List dan Arrays

In [54]:
# List
nums = [-2, -1, 0, 1, 2]
print(nums[2])

# Arrays
nums_np = np.array(nums)
print(nums_np[2])

0
0


In [55]:
# List
print(nums[-1])

# Arrays
print(nums_np[-1])

2
2


In [56]:
# List
print(nums[1:4])

# Arrays
print(nums_np[1:4])

[-1, 0, 1]
[-1  0  1]


### Basic 2-D indexing List dan Arrays

In [57]:
# 2-D list
nums2 = [ [1, 2, 3], [4, 5, 6] ]

# 2-D array
nums2_np = np.array(nums2)

In [58]:
# List
print(nums2[0][1])

# Arrays
print(nums2_np[0, 1])

2
2


In [59]:
# List comprehension
print([row[0] for row in nums2])

# Array
print(nums2_np[:, 0])

[1, 4]
[1 4]


### NumPy array boolean indexing

In [60]:
nums = [-2, -1, 0, 1, 2]
nums_np = np.array(nums)

In [61]:
# Boolean indexing
nums_np > 0

array([False, False, False,  True,  True])

In [62]:
nums_np[nums_np > 0]

array([1, 2])

Tidak ada pengindeksan boolean untuk list

In [64]:
# For loop (inefficient option)
pos = []
for num in nums:
    if num > 0:
        pos.append(num)
print(pos)

[1, 2]


In [65]:
# List comprehension (better option but not best)
pos = [num for num in nums if num > 0]
print(pos)

[1, 2]


### Practice with NumPy arrays

Mari kita berlatih *slicing* numpy array dan menggunakan konsep NumPy broadcasting. Ingat, broadcasting mengacu pada kemampuan array numpy untuk melakukan operasi vektor, sehingga mereka menjalankan pada semua elemen objek sekaligus.

In [70]:
nums = np.array([[ 1,  2,  3,  4,  5], [ 6,  7,  8,  9, 10]])

In [72]:
# Print second row of nums
print(nums[1,:])

[ 6  7  9  9 10]


In [73]:
# Print all elements of nums that are greater than six
print(nums[nums > 6])

[ 7  9  9 10]


In [74]:
# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

[[ 2  4  8  8 10]
 [12 14 18 18 20]]


In [75]:
# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[[ 1  2  5  4  5]
 [ 6  7 10  9 10]]


**Question**

Jika dibandingkan dengan objek list, apa dua keuntungan menggunakan `numpy` array ?

- `numpy` array berisi tipe data yang homogen (yang mengurangi konsumsi memori) dan memberikan kemampuan untuk menerapkan operasi pada semua elemen melalui broadcasting.

**Note** : Anda mengiris (*slicing*) numpy array seperti pro dan belajar bagaimana memanfaatkan konsep NumPy broadcasting. Menggunakan numpy array memungkinkan Anda untuk mengambil keuntungan dari sifat efisien array memori dan dengan mudah melakukan operasi matematika pada data Anda.

### Bringing it all together: Festivus!

Dalam latihan ini, Anda akan mengadakan pesta — Festivus jika Anda mau!

Anda memiliki daftar tamu (list `names`). Setiap tamu, dengan alasan apa pun, telah memutuskan untuk datang ke pesta dengan keterlambatan 10 menit. Sebagai contoh, Jerry muncul hingga pesta Festivus memasuki 10 menit, Kramer muncul 20 menit kemudian, dan seterusnya.

Kami ingin menulis beberapa baris kode sederhana, menggunakan fungsi bawaan Python yang telah kami bahas, untuk menyambut setiap tamu Anda dan memberi tahu mereka berapa menit keterlambatan mereka ke pesta Anda.

Mari kita sambut tamu Anda!

In [78]:
# Create a list of arrival times
arrival_times = [*range(10, 60, 10)]

print(arrival_times)

[10, 20, 30, 40, 50]


Anda menyadari jam Anda lebih cepat tiga menit.

In [79]:
# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

[ 7 17 27 37 47]


In [80]:
# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]
print(guest_arrivals)

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


In [81]:
def welcome_guest(guest_and_time):
    """
    Returns a welcome string for the guest_and_time tuple.
    
    Args:
        guest_and_time (tuple): The guest and time tuple to create
            a welcome string for.
            
    Returns:
        welcome_string (str): A string welcoming the guest to Festivus.
        'Welcome to Festivus {guest}... You're {time} min late.'
    
    """
    guest = guest_and_time[0]
    arrival_time = guest_and_time[1]
    welcome_string = "Welcome to Festivus {}... You're {} min late.".format(guest,arrival_time)
    return welcome_string

In [82]:
# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

Welcome to Festivus Jerry... You're 7 min late.
Welcome to Festivus Kramer... You're 17 min late.
Welcome to Festivus Elaine... You're 27 min late.
Welcome to Festivus George... You're 37 min late.
Welcome to Festivus Newman... You're 47 min late.


**Note** : Anda menggunakan fungsi bawaan Python seperti pro dan baik dalam cara Anda menulis kode Python yang efisien. Percaya atau tidak, ada cara untuk membuat baris kode sederhana ini menjadi lebih efisien! Kami akan membahasnya di bab mendatang, jadi lanjutkan untuk melihat caranya!